### PR TITLE
Fixed Saving Issues

### LINKED ISSUE #29: AutoExposure is not loaded until opening Post Processing GUI
**How to replicate**
1. Test A
- Load Preset
- Check AutoExposure Working
2. Test B
- Load Preset
- Turn Off AutoExposure
- Load Another Preset
- Check AutoExposure Working

### PR DESCRIPTION
**Pull request by hooh-hooah**
This fixes #29, #31

### CODE REVIEW

File: AI_Graphics/AI_Graphics/AIGraphics.cs [hunk 1]
```diff
@@ -116,10 +116,16 @@ private IEnumerator Start()
...
 
-            // It takes some time to fully loaded in studio to save/load stuffs.
-            yield return new WaitUntil(() => {
-                return (KoikatuAPI.GetCurrentGameMode() == GameMode.Studio) ? KKAPI.Studio.StudioAPI.InsideStudio && _skyboxManager != null : true;
-            });
+            if (KoikatuAPI.GetCurrentGameMode() == GameMode.Maker) {
+                yield return new WaitUntil(() => {
+                    return (KoikatuAPI.GetCurrentGameMode() == GameMode.Maker && _skyboxGO == null);
+                });
+                StartCoroutine(Start()); // Start Loop for Maker
```
Comment (ore-) [inline AI_Graphics/AI_Graphics/AIGraphics.cs:123]: isn't this a recursive call? we are in Start() itself, no?

File: AI_Graphics/AI_Graphics/AIGraphics.cs [hunk 2]
```diff
@@ -116,10 +116,16 @@ private IEnumerator Start()
             
             _inspector = new Inspector.Inspector(this);
 
-            // It takes some time to fully loaded in studio to save/load stuffs.
-            yield return new WaitUntil(() => {
-                return (KoikatuAPI.GetCurrentGameMode() == GameMode.Studio) ? KKAPI.Studio.StudioAPI.InsideStudio && _skyboxManager != null : true;
-            });
+            if (KoikatuAPI.GetCurrentGameMode() == GameMode.Maker) {
+                yield return new WaitUntil(() => {
+                    return (KoikatuAPI.GetCurrentGameMode() == GameMode.Maker && _skyboxGO == null);
```
Comment (ore-) [inline AI_Graphics/AI_Graphics/AIGraphics.cs:121]: isn't the maker check redundant? we wouldn't have been here otherwise.  don't quite understand what this fixes. is this a fix for entering maker a second time and aigraphics breaking? what actually breaks?

Comment (hooh-hooah) [reply AI_Graphics/AI_Graphics/AIGraphics.cs:121]: old 119-122: This used to be there to load default preset files. Since they're gone I commented it.
new 119-121: This condition will only run in Main Character Creation Menu. Addtional Information is in next comment.

File: AI_Graphics/AI_Graphics/Inspector/PresetInspector.cs [hunk 3]
```diff
@@ -42,8 +42,10 @@ internal static void Draw(PresetManager presetManager)
             _nameToSave = GUILayout.TextField(_nameToSave);
             bool isValidFileName = (0 != _nameToSave.Length && 256 >= _nameToSave.Length);
             bool isCue = (_nameCue == _nameToSave);
-            if (GUILayout.Button("Save", GUILayout.ExpandWidth(false)) && isValidFileName && !isCue )
+            if (GUILayout.Button("Save", GUILayout.ExpandWidth(false)) && isValidFileName && !isCue) {
                 presetManager.Save(_nameToSave);
+                _presetIndexCurrent = Array.IndexOf(presetManager.PresetNames, presetManager.CurrentPreset);
```
Comment (ore-) [inline AI_Graphics/AI_Graphics/Inspector/PresetInspector.cs:47]: Do you know why we would need this? The next Draw() call will do exactly this before the _presetIndexCurrent is used right?

File: AI_Graphics/AI_Graphics/AIGraphics.cs (hunk 1 above)
Comment (hooh-hooah) [reply AI_Graphics/AI_Graphics/AIGraphics.cs:123]: The reason why i inserted recursive call is Start() Coroutine is only called ONCE when the object has been initialized.
That means IBL will only can be used in first encounter of Character Maker.
As stated Issue #12, this makes IBL is not usable after closing character maker once.

So i did little trick, since this is async job, it will await till when IBL object is not valid in character maker.
After Awaiting Start() Coroutine detects Character Maker without IBL Instance, It will try to start Start() coroutine and await til it finds Character Maker without IBL Instance.

File: AI_Graphics/AI_Graphics/Inspector/PresetInspector.cs (hunk 3 above)
Comment (hooh-hooah) [reply AI_Graphics/AI_Graphics/Inspector/PresetInspector.cs:47]: Oh hell, it's supposed to be _presetIndexOld -.-

Comment (hooh-hooah) [reply AI_Graphics/AI_Graphics/Inspector/PresetInspector.cs]: Fixed with commit f8772a4
